#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(ggplot2)
library(dplyr)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("ChatGPT Data set and analysis"))

# Here's an example dataset with 5 columns and 25 rows that we can use for analysis:
set.seed(123)
data <- data.frame(
  id = 1:25,
  age = sample(18:60, 25, replace=TRUE),
  gender = sample(c("Male", "Female"), 25, replace=TRUE),
  income = round(runif(25, 20000, 100000), 2),
  education = sample(c("High School", "Bachelor's", "Master's"), 25, replace=TRUE)
)


ui <- fluidPage(
  titlePanel("Analysis of fictional demographic data generated by ChatGPT"),
  sidebarLayout(
    sidebarPanel(
      selectInput("x_var", "X-Axis Variable", choices = c("age", "income")),
      selectInput("y_var", "Y-Axis Variable", choices = c("education", "gender")),
      selectInput("plot_type", "Plot Type", choices = c("Scatterplot", "Boxplot"))
    ),
    mainPanel(
      plotOutput("plot")
    )
  )
)

server <- function(input, output) {
  output$plot <- renderPlot({
    if (input$plot_type == "Boxplot") {
      data %>%
        ggplot(aes(x = .data[[input$x_var]], y = .data[[input$y_var]])) +
        geom_boxplot() +
        labs(x = input$x_var, y = input$y_var)
    } else {
      data %>%
        ggplot(aes(x = .data[[input$x_var]], y = .data[[input$y_var]])) +
        geom_point() +
        ggtitle(paste("Plot of", input$x_var, "vs", input$y_var)) +
        labs(x = input$x_var, y = input$y_var)
    }
  })
}


# Run the application 
shinyApp(ui = ui, server = server)
deployApp()

